---

- name: Repalce disk on a kubernetes node
  hosts: k8s[1]
  become: true
  gather_facts: false

  tasks:
  - name: Get volume group info
    shell: vgs
    register: vgs_output

  - name: Get physical volume info
    shell: pvs
    register: pvs_output

  - name: Show volume info
    debug:
      msg:
          - "{{ vgs_output.stdout_lines }}"  
          - "{{ pvs_output.stdout_lines }}"
           
  - name: Pause to verify groups
    pause:


  - name: Drain the node
    shell: kubectl --kubeconfig /etc/kubernetes/admin.conf drain k8s-worker01 --ignore-daemonsets --delete-emptydir-data
    register: drain_output

  - debug:
      msg: "{{ drain_output.stdout_lines }}"

  - name: Pause to verify drain
    pause:


  - name: Backup containerd config
    copy:
      src: /etc/containerd/config.toml
      dest: /etc/containerd/config.toml_backup
      remote_src: true
      mode: preserve

  - name: Backup chrony config
    copy:
      src: /etc/chrony.conf
      dest: /etc/chrony.conf_backup
      remote_src: true
      mode: preserve
