---

- name: Restart httpd with condition
  hosts: k8s
  gather_facts: no

  vars:
    required: 'no'

  tasks:
    - name: Restart httpd
      systemd:
        name: nginx
        state: restarted
      when: required is defined and required == 'yes'
