---

- name: Add dns addresses
  hosts: rhnodes
  gather_facts: no
  become: yes


  tasks:

  - name: Add DNS entries 
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: 192.168.1.17 Ansible
