
- name: Find files
  hosts: localhost
  gather_facts: no
  become: true


  tasks:
    - name: Find file
      find:
        paths: /home
      register: find_output

    - debug:
        var: find_output.files






