---
- name: Update
  hosts: 192.168.1.11
  become: true
  gather_facts: no

  tasks:

  - name: Backup of the configuration
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
    loop:
    - src: /etc/kubernetes/
      dest: /tmp/kubernetes
    - src: /home/ezmeralsa/.kube/
      dest: /tmp/kube_config
